import 'package:flutter/material.dart';

import '../../app/theme.dart';
import '../../l10n/app_localizations.dart';

/// Static emergency quick card data. No model dependency — these render
/// instantly even if Gemma fails to load (safety net, docs/prd.md M4).
///
/// Bilingual (2026-09-09): the Cards tab used to render [titleBn] /
/// [stepsBn] directly, so the English locale still showed Bangla.
/// Each card now carries parallel English fields; [title] / [steps]
/// pick by the active locale. Bangla fields stay public — the AI
/// handoff and the on-device model prompts are Bangla by design.
class QuickCard {
  final String id;
  final String titleBn;
  final String titleEn;
  final IconData icon;
  final Color color;
  final List<String> stepsBn;
  final List<String> stepsEn;

  const QuickCard({
    required this.id,
    required this.titleBn,
    required this.titleEn,
    required this.icon,
    required this.color,
    required this.stepsBn,
    required this.stepsEn,
  });

  /// Locale-aware title for UI.
  String title(BuildContext context) =>
      _isBn(context) ? titleBn : titleEn;

  /// Locale-aware steps for UI.
  List<String> steps(BuildContext context) =>
      _isBn(context) ? stepsBn : stepsEn;

  static bool _isBn(BuildContext context) =>
      AppLocalizations.of(context).localeName.startsWith('bn');
}

const kQuickCards = <QuickCard>[
  // ── Informational cards: ocean blue accent (brand primary) ────────────
  QuickCard(
    id: 'ors',
    titleBn: 'ORS তৈরি',
    titleEn: 'Making ORS',
    icon: Icons.water_drop_rounded,
    color: ShongjogTheme.ocean,
    stepsBn: [
      '১ লিটার পরিষ্কার পানি নিন',
      '৬ চা-চামচ চিনি ও আধা চা-চামচ লবণ মেশান',
      'ভালো করে নাড়ুন যতক্ষণ না দ্রবীভূত হয়',
      'একটু একটু করে বারবার খাওয়ান',
      'বানানো ORS কয়েক ঘণ্টা পর নতুন করে বানান',
    ],
    stepsEn: [
      'Take 1 litre of clean water',
      'Mix 6 teaspoons of sugar and half a teaspoon of salt',
      'Stir well until fully dissolved',
      'Give it to drink in small sips, repeatedly',
      'Discard and remake the ORS after a few hours',
    ],
  ),
  QuickCard(
    id: 'water',
    titleBn: 'পানি শুদ্ধ করা',
    titleEn: 'Purifying Water',
    icon: Icons.local_drink_rounded,
    color: ShongjogTheme.ocean,
    stepsBn: [
      'পানি ফুটিয়ে নিন (কমপক্ষে ১ মিনিট)',
      'ফুটানো সম্ভব না হলে পরিষ্কার কাপড়ে ছেঁকে নিন',
      'স্বচ্ছ প্লাস্টিক বোতলে ৬ ঘণ্টা রোদে রাখুন',
      'ORS-এর জন্য এই পানি ব্যবহার করুন',
    ],
    stepsEn: [
      'Boil the water (for at least 1 minute)',
      'If boiling is not possible, filter it through a clean cloth',
      'Leave it in a clear plastic bottle in sunlight for 6 hours',
      'Use this water for making ORS',
    ],
  ),
  QuickCard(
    id: 'shelter',
    titleBn: 'আশ্রয়কেন্দ্র',
    titleEn: 'Shelter',
    icon: Icons.shield_rounded,
    color: ShongjogTheme.ocean,
    stepsBn: [
      'নিকটস্থ সাইক্লোন শেল্টারে যান',
      'খাবার ও পানি সঙ্গে রাখুন (৩ দিনের)',
      'মূল্যবান কাগজপত্র সঙ্গে নিন',
      'গাছ ও বৈদ্যুতিক খুঁটি থেকে দূরে থাকুন',
    ],
    stepsEn: [
      'Go to the nearest cyclone shelter',
      'Keep food and water with you (3 days\' worth)',
      'Take important documents with you',
      'Stay away from trees and electricity poles',
    ],
  ),
  QuickCard(
    id: 'drowning',
    titleBn: 'ডুবে যাওয়া ব্যক্তি',
    titleEn: 'Drowning Person',
    icon: Icons.pool_rounded,
    color: ShongjogTheme.ocean,
    stepsBn: [
      'নিজে পানিতে নামবেন না — দড়ি বা লাঠি দিয়ে টানুন',
      'সাঁতার না জানলে কখনো পানিতে ঝাঁপাবেন না',
      'ব্যক্তিকে পানির বাইরে টেনে আনুন',
      'নাকে-মুখে পানি থাকলে গায়ের ওপর চাপ দিন',
      'শ্বাস না নিলে ৩০ সেকেন্ড CPR দিন',
      'দ্রুত ৯৯৯ এ কল করুন',
    ],
    stepsEn: [
      'Do not enter the water yourself — pull with a rope or pole',
      'Never jump in if you cannot swim',
      'Pull the person out of the water',
      'If water is in the nose or mouth, press on the chest',
      'If not breathing, start CPR for 30 seconds',
      'Call 999 quickly',
    ],
  ),
  // ── Emergency cards: alertRed accent (sparingly, never decorative) ───
  QuickCard(
    id: 'snakebite',
    titleBn: 'সাপের কামড়',
    titleEn: 'Snakebite',
    icon: Icons.dangerous_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'কাটবেন না, চুষবেন না, বরফ দেবেন না',
      'আক্রান্ত স্থান নিচু রাখুন ও নড়াচড়া কমান',
      'শিকারকে শান্ত রাখুন — দৌড় নয়',
      'দ্রুত নিকটস্থ হাসপাতালে যান',
      'জরুরি হলে ৯৯৯ এ কল করুন',
    ],
    stepsEn: [
      'Do not cut, suck, or apply ice',
      'Keep the bitten limb lowered and limit movement',
      'Keep the victim calm — no running',
      'Get to the nearest hospital quickly',
      'Call 999 in an emergency',
    ],
  ),
  QuickCard(
    id: 'diarrhea',
    titleBn: 'প্রচণ্ড ডায়রিয়া',
    titleEn: 'Severe Diarrhea',
    icon: Icons.medical_information_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'বারবার ORS খাওয়ান',
      'প্রতিবার পাতলা পায়খানার পর ১ গ্লাস পানিঝুলি',
      'শিশু বমি করলে অল্প অল্প করে বারবার দিন',
      'রক্ত মিশ্রিত বা ২৪ ঘণ্টার বেশি হলে ডাক্তার দেখান',
    ],
    stepsEn: [
      'Give ORS repeatedly',
      'One glass of fluids after every loose stool',
      'If a child is vomiting, give fluids in small amounts often',
      'See a doctor if there is blood or it lasts over 24 hours',
    ],
  ),
  QuickCard(
    id: 'bleeding',
    titleBn: 'রক্তপাত বন্ধ',
    titleEn: 'Stopping Bleeding',
    icon: Icons.healing_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'পরিষ্কার কাপড় দিয়ে জায়গায় চাপ দিন',
      'আক্রান্ত অংশ হৃদয়ের চেয়ে উঁচুতে রাখুন',
      '১০ মিনিট ধরে চাপ অব্যাহত রাখুন',
      'না থামলে ৯৯৯ এ কল করুন',
    ],
    stepsEn: [
      'Press on the wound with a clean cloth',
      'Raise the injured part above heart level',
      'Keep applying pressure for 10 minutes',
      'Call 999 if it does not stop',
    ],
  ),
  QuickCard(
    id: 'fever',
    titleBn: 'জ্বর হলে করণীয়',
    titleEn: 'What to Do for Fever',
    icon: Icons.thermostat_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'প্রচুর পানি ও তরল খাওয়ান',
      'হালকা ঢিলেঢালা কাপড় পরুন',
      'প্যারাসিটামল সঠিক ডোজে দিন (বয়স অনুযায়ী)',
      'কপালে ও বগলে ঠাণ্ডা পানির সেঁক দিন',
      '৩ দিনের বেশি জ্বর বা ১০২°F উপরে হলে ডাক্তার দেখান',
      'শিশুর দাঁড়ি-ঝাড়া খিঁচুনি বা অজ্ঞান হলে ৯৯৯ কল করুন',
    ],
    stepsEn: [
      'Give plenty of water and fluids',
      'Dress in light, loose clothing',
      'Give paracetamol at the correct dose (by age)',
      'Apply cool wet compresses to the forehead and armpits',
      'See a doctor if fever lasts over 3 days or exceeds 102°F',
      'Call 999 if a child has convulsions or loses consciousness',
    ],
  ),
  QuickCard(
    id: 'flood',
    titleBn: 'বন্যা হলে করণীয়',
    titleEn: 'What to Do in a Flood',
    icon: Icons.flood_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'উঁচু স্থানে আশ্রয় নিন যেমন ছাদ বা উঁচু মাঠ',
      'বন্যার নোংরা বা দূষিত পানি পান করবেন না',
      'বৈদ্যুতিক তার ও পোল স্পর্শ করা থেকে বিরত থাকুন',
      'মোবাইল ফোন ও জরুরি আলো চার্জ দিয়ে রাখুন',
      'বিশুদ্ধ বা ফুটানো পানি এবং শুকনো খাবার সাথে রাখুন',
      'জরুরি প্রয়োজনে ৯৯৯ এ কল করুন',
    ],
    stepsEn: [
      'Take shelter on high ground such as a roof or upper field',
      'Do not drink dirty or contaminated floodwater',
      'Avoid touching electrical wires and poles',
      'Keep mobile phones and emergency lights charged',
      'Keep purified or boiled water and dry food with you',
      'Call 999 in an emergency',
    ],
  ),
  QuickCard(
    id: 'cyclone_tornado',
    titleBn: 'ঘূর্ণিঝড় ও টর্নেডো',
    titleEn: 'Cyclone and Tornado',
    icon: Icons.cyclone_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'আবহাওয়ার সতর্কবার্তা শুনুন এবং গুরুত্ব দিন',
      'দ্রুত নিরাপদ স্থানে বা সাইক্লোন শেল্টারে যান',
      'ঘরের সব দরজা-জানালা শক্তভাবে বন্ধ রাখুন',
      'মূল্যবান কাগজপত্র ও ওষুধ জলরোধী ব্যাগে রাখুন',
      'ঝড় চলাকালীন ঘরের বাইরে বের হবেন না',
      'বৈদ্যুতিক ও গ্যাসের সংযোগ বন্ধ রাখুন',
    ],
    stepsEn: [
      'Listen to weather warnings and take them seriously',
      'Move quickly to a safe place or cyclone shelter',
      'Keep all doors and windows firmly shut',
      'Keep documents and medicines in a waterproof bag',
      'Do not go outside during the storm',
      'Keep electricity and gas connections off',
    ],
  ),
  QuickCard(
    id: 'earthquake',
    titleBn: 'ভূমিকম্প হলে করণীয়',
    titleEn: 'What to Do in an Earthquake',
    icon: Icons.warning_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'ভূমিকম্পের সময় শান্ত থাকুন এবং আতঙ্কিত হবেন না',
      'ঘরের ভেতরে থাকলে শক্ত টেবিল বা খাটের নিচে অবস্থান নিন',
      'মাথা ও ঘাড় হাত বা বালিশ দিয়ে ঢেকে রাখুন',
      'বহুতল ভবন থেকে নামার সময় লিফট ব্যবহার করবেন না',
      'বাইরে থাকলে ভবন, গাছ ও বৈদ্যুতিক খুঁটি থেকে দূরে থাকুন',
      'ভূমিকম্পের পর গ্যাসের গন্ধ বা ফাটল পরীক্ষা করুন',
    ],
    stepsEn: [
      'Stay calm during the quake — do not panic',
      'If indoors, take cover under a sturdy table or bed',
      'Protect your head and neck with your hands or a pillow',
      'Do not use elevators when leaving a multi-storey building',
      'If outdoors, stay away from buildings, trees and power poles',
      'After the quake, check for gas leaks and cracks',
    ],
  ),
  QuickCard(
    id: 'fire_incident',
    titleBn: 'অগ্নিকাণ্ড হলে করণীয়',
    titleEn: 'What to Do in a Fire',
    icon: Icons.local_fire_department_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'আতঙ্কিত না হয়ে দ্রুত ভবন থেকে বের হয়ে যান',
      'ধোঁয়া থাকলে নিচু হয়ে হামাগুড়ি দিয়ে চলুন',
      'কাপড়ে আগুন লাগলে দৌড়াবেন না, মাটিতে গড়াগড়ি দিন',
      'বের হওয়ার দরজা না পেলে জানালায় এসে সাহায্য চান',
      'ফায়ার সার্ভিস বা জরুরি সাহায্যের জন্য ৯৯৯ এ কল করুন',
      'পুড়ে যাওয়া স্থানে অন্তত ১০-২০ মিনিট ঠাণ্ডা পানি দিন',
    ],
    stepsEn: [
      'Exit the building quickly without panicking',
      'If there is smoke, stay low and crawl',
      'If clothes catch fire, do not run — roll on the ground',
      'If no exit is available, go to a window and call for help',
      'Call 999 for the fire service or emergency help',
      'Run cool water over burns for at least 10–20 minutes',
    ],
  ),
  QuickCard(
    id: 'landslide',
    titleBn: 'ভূমিধস হলে করণীয়',
    titleEn: 'What to Do in a Landslide',
    icon: Icons.landslide_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'পাহাড়ের পাদদেশে ঝুঁকিপূর্ণ বসতি পরিহার করুন',
      'টানা ভারী বৃষ্টিপাত হলে নিরাপদ আশ্রয়ে চলে যান',
      'পাহাড়ি ঢাল দিয়ে কাদা বা পাথর ধসে পড়তে দেখলে নিরাপদ দূরত্বে যান',
      'ধসের পর মাটিতে আটকে পড়া মানুষের জন্য দ্রুত উদ্ধার তৎপরতা চালান',
      'বৈদ্যুতিক তার ও ভাঙা গাছপালা থেকে দূরে থাকুন',
      'জরুরি সাহায্যের জন্য দ্রুত ৯৯৯ এ কল করুন',
    ],
    stepsEn: [
      'Avoid risky settlements at the foot of hills',
      'Move to safe shelter during continuous heavy rain',
      'If mud or rocks slide down a slope, move to a safe distance',
      'After a slide, act quickly to rescue anyone trapped',
      'Stay away from power lines and broken trees',
      'Call 999 quickly for emergency help',
    ],
  ),
  QuickCard(
    id: 'lightning_strike',
    titleBn: 'বজ্রপাত হলে করণীয়',
    titleEn: 'What to Do in Lightning',
    icon: Icons.bolt_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'মেঘের ডাক শুনলে দ্রুত পাকা বাড়ির ভেতরে বা আশ্রয়কেন্দ্রে যান',
      'বজ্রপাতের সময় খোলা মাঠ বা বড় গাছের নিচে থাকবেন না',
      'ধাতব বস্তু, বৈদ্যুতিক খুঁটি ও মোবাইল টাওয়ার থেকে দূরে থাকুন',
      'বৈদ্যুতিক যন্ত্রপাতি স্পর্শ করবেন না এবং সংযোগ বিচ্ছিন্ন রাখুন',
      'পানি থেকে দ্রুত উঠে পড়ুন এবং জলাশয় থেকে দূরে থাকুন',
      'আক্রান্ত ব্যক্তিকে দ্রুত ডাক্তারের কাছে নিয়ে যান ও প্রয়োজনে CPR দিন',
    ],
    stepsEn: [
      'On hearing thunder, quickly go inside a solid building or shelter',
      'During lightning, do not stay in open fields or under tall trees',
      'Keep away from metal objects, power poles and mobile towers',
      'Do not touch electrical appliances and keep them unplugged',
      'Get out of water quickly and stay away from water bodies',
      'Take strike victims to a doctor fast; give CPR if needed',
    ],
  ),
  QuickCard(
    id: 'riverbank_erosion',
    titleBn: 'নদীভাঙন হলে করণীয়',
    titleEn: 'What to Do in Riverbank Erosion',
    icon: Icons.waves_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'নদীভাঙনপ্রবণ এলাকায় বসতি স্থাপনে সতর্ক থাকুন',
      'ভাঙনের আলামত দেখা দিলে মূল্যবান সামগ্রী নিয়ে নিরাপদ স্থানে যান',
      'জরুরি আশ্রয়ের জন্য স্থানীয় কর্তৃপক্ষের সাথে যোগাযোগ রাখুন',
      'পরিবারের সদস্যদের সাথে নিরাপদ যোগাযোগ ব্যবস্থা ঠিক করে রাখুন',
      'ভাঙনকবলিত ঝুঁকিপূর্ণ খাড়া পাড় থেকে সবসময় দূরে থাকুন',
      'বন্যা ও ভাঙনকালীন সাহায্য পাওয়ার জন্য ৯৯৯ এ যোগাযোগ করুন',
    ],
    stepsEn: [
      'Be cautious about settling in erosion-prone areas',
      'At the first signs of erosion, take valuables to a safe place',
      'Stay in touch with local authorities for emergency shelter',
      'Set up a safe way to communicate with family members',
      'Always keep away from risky steep banks being eroded',
      'Contact 999 for help during floods and erosion',
    ],
  ),
  QuickCard(
    id: 'heatwave',
    titleBn: 'তীব্র দাবদাহ হলে করণীয়',
    titleEn: 'What to Do in a Heatwave',
    icon: Icons.wb_sunny_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'দিনের তীব্র রোদে সরাসরি যাওয়া এড়িয়ে চলুন',
      'প্রচুর পরিমাণে পানি এবং তরল খাবার বা স্যালাইন পান করুন',
      'হালকা, ঢিলেঢালা এবং সুতি কাপড় পরিধান করুন',
      'রোদে বের হতে হলে ছাতা বা চওড়া টুপি ব্যবহার করুন',
      'অতিরিক্ত পরিশ্রমের কাজ এড়িয়ে চলুন এবং ঠাণ্ডা স্থানে বিশ্রাম নিন',
      'হিট স্ট্রোক বা অজ্ঞান হওয়ার লক্ষণ দেখলে দ্রুত হাসপাতালে নিয়ে যান',
    ],
    stepsEn: [
      'Avoid going out in the strong midday sun',
      'Drink plenty of water, fluids, or saline',
      'Wear light, loose cotton clothing',
      'Use an umbrella or wide hat when out in the sun',
      'Avoid strenuous work and rest in a cool place',
      'At signs of heatstroke or fainting, get to a hospital fast',
    ],
  ),
  QuickCard(
    id: 'cold_wave',
    titleBn: 'শৈত্যপ্রবাহ হলে করণীয়',
    titleEn: 'What to Do in a Cold Wave',
    icon: Icons.ac_unit_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'পর্যাপ্ত পরিমাণে গরম ও ভারী সুতি বা পশমি কাপড় পরিধান করুন',
      'মাথা, কান ও হাত-পা ভালোভাবে ঢেকে রাখুন',
      'উষ্ণ পানীয় ও পুষ্টিকর গরম খাবার গ্রহণ করুন',
      'ঘর ও চারপাশ যথাসম্ভব উষ্ণ রাখার ব্যবস্থা করুন',
      'শিশু এবং বয়স্কদের ঘরের ভেতরে রাখুন ও বাড়তি যত্ন নিন',
      'ঠাণ্ডাজনিত তীব্র শ্বাসকষ্ট বা অসুস্থতায় ডাক্তারের পরামর্শ নিন',
    ],
    stepsEn: [
      'Wear enough warm, heavy cotton or woolen clothes',
      'Keep the head, ears, hands and feet well covered',
      'Take warm drinks and nutritious hot food',
      'Keep the house and surroundings as warm as possible',
      'Keep children and the elderly indoors with extra care',
      'Consult a doctor for severe cold-related breathing trouble',
    ],
  ),
  QuickCard(
    id: 'tsunami',
    titleBn: 'সুনামি হলে করণীয়',
    titleEn: 'What to Do in a Tsunami',
    icon: Icons.tsunami_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'উপকূলীয় এলাকায় তীব্র ভূমিকম্প অনুভূত হলে দ্রুত উঁচু স্থানে যান',
      'সমুদ্রের পানি হঠাৎ সরে যেতে দেখলে উপকূল থেকে দূরে চলে যান',
      'সুনামির প্রথম ঢেউয়ের পর নিরাপদ স্থানে থাকুন, আরও ঢেউ আসতে পারে',
      'উপকূলীয় নদী ও খালের কাছাকাছি থাকবেন না',
      'আবহাওয়ার খবর ও সুনামির সতর্কবার্তার দিকে খেয়াল রাখুন',
      'আক্রান্তদের সাহায্য করতে স্থানীয় বিপর্যয় বাহিনীর সাথে যোগাযোগ করুন',
    ],
    stepsEn: [
      'If a strong quake is felt near the coast, move to high ground fast',
      'If the sea suddenly recedes, move away from the coast',
      'Stay in a safe place after the first wave — more may follow',
      'Do not stay near coastal rivers and canals',
      'Keep track of weather news and tsunami warnings',
      'Contact local disaster forces to help the affected',
    ],
  ),
  QuickCard(
    id: 'drought',
    titleBn: 'খরা হলে করণীয়',
    titleEn: 'What to Do in a Drought',
    icon: Icons.wb_sunny_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'পানি সাশ্রয় করুন এবং গৃহস্থালির কাজে পানির অপচয় বন্ধ করুন',
      'বৃষ্টির পানি ধরে রাখার ও সংরক্ষণের ব্যবস্থা গ্রহণ করুন',
      'খরাসহনশীল ফসল চাষে জোর দিন এবং জমিতে পরিমিত সেচ দিন',
      'খাবারের জন্য নিরাপদ পানি ফুটিয়ে বা ছেঁকে ব্যবহার করুন',
      'গবাদি পশুর জন্য পর্যাপ্ত পানীয় জল ও খাদ্যের ব্যবস্থা রাখুন',
      'তীব্র খাদ্য বা পানীয় সংকটে স্থানীয় প্রশাসনের সাহায্য নিন',
    ],
    stepsEn: [
      'Save water and stop wasting it on household chores',
      'Set up rainwater harvesting and storage',
      'Prioritize drought-tolerant crops and irrigate moderately',
      'Boil or filter water before using it for food',
      'Keep enough drinking water and feed for livestock',
      'Seek help from local administration in severe shortages',
    ],
  ),
  QuickCard(
    id: 'chemical_disaster',
    titleBn: 'রাসায়নিক দুর্ঘটনা',
    titleEn: 'Chemical Accident',
    icon: Icons.science_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'রাসায়নিক গ্যাস বা ধোঁয়া ছড়ালে মুখ ও নাক ভেজা কাপড় দিয়ে ঢেকে রাখুন',
      'বাতাসের বিপরীত দিকে অথবা উঁচুতে নিরাপদ স্থানে চলে যান',
      'ঘরের ভেতরে থাকলে সব দরজা-জানালা এবং ভেন্টিলেটর বন্ধ করুন',
      'ত্বকে ক্ষতিকারক রাসায়নিক লাগলে দ্রুত প্রচ্ছ পানি দিয়ে ধুয়ে ফেলুন',
      'জরুরি উদ্ধার ও সাহায্যের জন্য দ্রুত ৯৯৯ এ কল করুন',
      'ডাক্তারের পরামর্শ ছাড়া কোনো মলম বা ওষুধ ক্ষতে লাগাবেন না',
    ],
    stepsEn: [
      'If chemical gas or smoke spreads, cover mouth and nose with a wet cloth',
      'Move upwind or to a safe elevated place',
      'If indoors, close all doors, windows and vents',
      'If harmful chemicals touch skin, rinse quickly with plenty of water',
      'Call 999 fast for emergency rescue and help',
      'Do not apply any ointment or medicine without a doctor\'s advice',
    ],
  ),
  // ── Triage-routed cards (wizard terminal CTAs) ─────────────────────
  QuickCard(
    id: 'cpr',
    titleBn: 'সিপিআর (হৃদযন্ত্রের ম্যাসাজ)',
    titleEn: 'CPR (Cardiac Massage)',
    icon: Icons.favorite_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'ব্যক্তি সমতল ও শক্ত জায়গায় শুইয়ে নিন',
      'বুকের মাঝখানে দুই হাত রেখে ১১০ বার/মিনিট হারে চাপ দিন',
      'প্রতি ৩০ টি চাপের পর ২ টি শ্বাস দিন (৩০:২ অনুপাত)',
      'শিশুর ক্ষেত্রে এক হাত বা দুই আঙুল দিয়ে আলতো চাপ দিন',
      'অ্যাম্বুলেন্স বা ৯৯৯ না আসা পর্যন্ত থামবেন না',
    ],
    stepsEn: [
      'Lay the person flat on a firm surface',
      'Place both hands on the center of the chest and press at 110/min',
      'After every 30 compressions give 2 breaths (30:2 ratio)',
      'For a child, press gently with one hand or two fingers',
      'Do not stop until the ambulance or 999 arrives',
    ],
  ),
  QuickCard(
    id: 'escalation',
    titleBn: '৯৯৯ কিভাবে কল করবেন',
    titleEn: 'How to Call 999',
    icon: Icons.phone_in_talk_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      '৯৯৯ নম্বরে কল করুন (ফোন অ্যাপ খুলবে)',
      'অপারেটরের প্রশ্নের উত্তর শান্তভাবে দিন',
      'আপনার অবস্থান (এলাকা, ল্যান্ডমার্ক) স্পষ্ট করে বলুন',
      'কী হয়েছে — ছোট করে বলুন (যেমন: "ব্যক্তি অজ্ঞান")',
      'প্রাথমিক চিকিৎসা চলাকালীন ফোন কাটবেন না',
      'নিকটস্থ পরিবার বা প্রতিবেশীকেও জানান',
    ],
    stepsEn: [
      'Call 999 (the phone app will open)',
      'Answer the operator\'s questions calmly',
      'State your location clearly (area, landmark)',
      'Say briefly what happened (e.g. "person unconscious")',
      'Do not hang up while giving first aid',
      'Also inform nearby family or neighbours',
    ],
  ),
  QuickCard(
    id: 'choking',
    titleBn: 'শ্বাসরোধ (আটকে যাওয়া)',
    titleEn: 'Choking',
    icon: Icons.air_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'ব্যক্তি যদি কাশি দিতে পারে — কাশি দিতে উৎসাহিত করুন',
      'কাশি বন্ধ হয়ে গেলে পিঠে ৫ বার জোরে চাপ দিন',
      'তারপর পেটের উপর ৫ বার হিথলিক চাপ দিন (হেইমলিখ)',
      'চাপ দেওয়ার সময় ব্যক্তিকে সামনে ঝুঁকিয়ে রাখুন',
      'শিশুর ক্ষেত্রে এক হাতে পিঠে চাপ দিন, অন্য হাতে পেটে',
      'বস না বের হলে ৯৯৯ কল করুন এবং পুনরাবৃত্তি করুন',
    ],
    stepsEn: [
      'If the person can cough — encourage them to cough',
      'If coughing stops, give 5 firm back blows',
      'Then give 5 abdominal thrusts (Heimlich)',
      'Keep the person leaning forward while delivering thrusts',
      'For a child: back blows with one hand, abdominal with the other',
      'If the object does not come out, call 999 and repeat',
    ],
  ),
  QuickCard(
    id: 'burn',
    titleBn: 'গুরুতর পোড়া',
    titleEn: 'Severe Burns',
    icon: Icons.local_fire_department_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'পোড়া স্থানে ঠাণ্ডা (কুসুম-গরম) পানি ২০ মিনিট চলমান রাখুন',
      'বরফ বা আঠা ব্যবহার করবেন না',
      'আঁটসাঁট আংটি, ঘড়ি বা গয়না থাকলে খুলে দিন',
      'পরিষ্কার, ঢিলেঢালা কাপড় বা প্লাস্টিক র্যাপ দিয়ে ঢাকুন',
      'ফোসকা ফাটাবেন না, মলম লাগাবেন না',
      'গুরুতর পোড়া হলে দ্রুত ৯৯৯ কল করুন বা হাসপাতালে যান',
    ],
    stepsEn: [
      'Run cool (lukewarm) water over the burn for 20 minutes',
      'Do not use ice or adhesive substances',
      'Remove tight rings, watches or jewelry',
      'Cover with a clean, loose cloth or plastic wrap',
      'Do not burst blisters or apply ointment',
      'For severe burns, call 999 or go to a hospital fast',
    ],
  ),
  QuickCard(
    id: 'recovery_position',
    titleBn: 'রিকভারি পজিশন',
    titleEn: 'Recovery Position',
    icon: Icons.accessibility_new_rounded,
    color: ShongjogTheme.alert,
    stepsBn: [
      'ব্যক্তিকে পাশ ফিরিয়ে শুইয়ে দিন (কাত হয়ে)',
      'নিচের পা সোজা, উপরের পা ভাঁজ করে হাঁটু ভূমিতে রাখুন',
      'মাথা পেছনে হেলিয়ে মুখ নিচুর দিকে রাখুন',
      'শ্বাসপথ পরিষ্কার রাখতে মুখ থেকে থুতু বা বমি বের করুন',
      'গরম কাপড় দিয়ে ঢেকে দিন — শরীর উষ্ণ রাখুন',
      'প্রতি ১–২ মিনিট শ্বাস ও নাড়ি পরীক্ষা করুন',
    ],
    stepsEn: [
      'Roll the person onto their side',
      'Keep the lower leg straight; bend the upper leg at the knee',
      'Tilt the head back with the face angled downward',
      'Let saliva or vomit drain from the mouth to keep the airway clear',
      'Cover with warm cloth — keep the body warm',
      'Check breathing and pulse every 1–2 minutes',
    ],
  ),
];
