/// Pure-Dart triage decision tree.
///
/// Walks a fixed sequence of yes/no questions and routes to one of
/// eight terminal nodes: cpr, bleeding, drowning, snakebite,
/// unconsciousBreathing, burn, choking, or escalation999. The tree
/// is a list, not a recursive graph — that keeps it unit-testable
/// and easy to translate to a UI wizard.
///
/// Content is restricted to the WHO/BDRCS/MoDMR/BMD/CDC/IFRC
/// first-aid whitelist; nothing here is generated by an LLM.
enum TriageRoute {
  cpr,
  bleeding,
  drowning,
  snakebite,
  unconsciousBreathing,
  burn,
  choking,
  escalation999,
}

/// A single yes/no question. Routes the user to one of two
/// follow-up questions OR to a terminal [TriageRoute].
class TriageQuestion {
  final String id;
  final String question;
  final TriageBranch yesBranch;
  final TriageBranch noBranch;

  const TriageQuestion._(this.id, this.question,
      {required this.yesBranch, required this.noBranch});
}

/// Tagged union: a question either routes to a [TriageRoute]
/// (terminal node) or to another [TriageQuestion].
class TriageBranch {
  final TriageRoute? route;
  final String? nextQuestionId;
  const TriageBranch.route(this.route) : nextQuestionId = null;
  const TriageBranch.next(this.nextQuestionId) : route = null;
}

class TriageTree {
  /// Ordered list of questions. The tree starts at the first.
  /// Note: 'conscious=no' routes to a separate 'breathingUnconscious'
  /// question so we can distinguish the recovery-position case
  /// (unconscious + breathing) from the CPR case (unconscious + not
  /// breathing). The latter still terminates at the same `cpr` route.
  static const List<TriageQuestion> questions = [
    TriageQuestion._(
      'conscious',
      'ব্যক্তি কি সচেতন?',
      yesBranch: TriageBranch.next('breathing'),
      noBranch: TriageBranch.next('breathingUnconscious'),
    ),
    TriageQuestion._(
      'breathing',
      'শ্বাস নিচ্ছে?',
      yesBranch: TriageBranch.next('bleeding'),
      noBranch: TriageBranch.route(TriageRoute.cpr),
    ),
    TriageQuestion._(
      'breathingUnconscious',
      'শ্বাস নিচ্ছে?',
      yesBranch: TriageBranch.route(TriageRoute.unconsciousBreathing),
      noBranch: TriageBranch.route(TriageRoute.cpr),
    ),
    TriageQuestion._(
      'bleeding',
      'গুরুতর রক্তপাত হচ্ছে?',
      yesBranch: TriageBranch.route(TriageRoute.bleeding),
      noBranch: TriageBranch.next('water'),
    ),
    TriageQuestion._(
      'water',
      'পানিতে ছিল বা ডুবেছে?',
      yesBranch: TriageBranch.route(TriageRoute.drowning),
      noBranch: TriageBranch.next('snakebite'),
    ),
    TriageQuestion._(
      'snakebite',
      'সাপে কামড়েছে?',
      yesBranch: TriageBranch.route(TriageRoute.snakebite),
      noBranch: TriageBranch.next('burn'),
    ),
    TriageQuestion._(
      'burn',
      'গুরুতর পোড়া?',
      yesBranch: TriageBranch.route(TriageRoute.burn),
      noBranch: TriageBranch.next('choking'),
    ),
    TriageQuestion._(
      'choking',
      'কথা বলতে বা কাশি দিতে পারছে?',
      yesBranch: TriageBranch.route(TriageRoute.escalation999),
      noBranch: TriageBranch.route(TriageRoute.choking),
    ),
  ];

  /// Walk the tree given a sequence of answers (true == yes,
  /// false == no). Stops at the first terminal route. If answers
  /// run out before a terminal node, returns
  /// [TriageRoute.escalation999] — the safe default.
  static TriageRoute walk(List<bool> answers) {
    String? nextId = questions.first.id;
    int i = 0;
    while (nextId != null) {
      if (i >= answers.length) {
        return TriageRoute.escalation999;
      }
      final q = questions.firstWhere((q) => q.id == nextId);
      final branch = answers[i] ? q.yesBranch : q.noBranch;
      i++;
      if (branch.route != null) return branch.route!;
      nextId = branch.nextQuestionId;
    }
    return TriageRoute.escalation999;
  }
}